# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='temp_offline',
        ),
    ]
