# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_remove_board_temp_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='temp_offline',
            field=models.BooleanField(default=False),
        ),
    ]
